### ISSUE TITLE
Howto make text to number

### ISSUE THREAD

**Issue by zsdevX** [donglee-afar/logdeep#1]
As the title describe, are there some  requirement to convert text to numbers?

**Comment by donglee-afar** [comment]
I assume here that the **text** you say corresponds to the **original log**, and the **number** corresponds to the **log template**.
To fairly compare model performance, I used the log template extracted by others [here](https://www.cs.utah.edu/~mind/papers/deeplog_misc.html)
If you want to extarct it by your self, I recommend using **Drain** which is the most effective log parsing method. Check it here! [logparser](https://github.com/logpai/logparser).

**Comment by zsdevX** [comment]
@donglee-afar  see, thanks.

**Comment by HankKung** [comment]
> I assume here that the **text** you say corresponds to the **original log**, and the **number** corresponds to the **log template**.
> To fairly compare model performance, I used the log template extracted by others [here](https://www.cs.utah.edu/~mind/papers/deeplog_misc.html)
> If you want to extarct it by your self, I recommend using **Drain** which is the most effective log parsing method. Check it here! [logparser](https://github.com/logpai/logparser).

Hi @donglee-afar,  the link to the extracted templated is failed. Do you have any clue or alternative?

**Comment by d0ng1ee** [comment]
http://people.iiis.tsinghua.edu.cn/~weixu/200nodes.rar
