### ISSUE TITLE
question about bgl dataset

### ISSUE THREAD

**Issue by Yanyyy** [donglee-afar/logdeep#11]
Hi, thank you for making this amazing project.

I have some question when I use the BGL dataset to train and test. In the logdeep/dataset/sample.py you use 'hdfs/event2semantic_vec.json', I have no idea what is the function of this file. And when I use the BGL dataset, how I generate this file? Or I needn't this file? If it is not needed, how should I modify sample.py?

looking forward to your reply.

**Comment by d0ng1ee** [comment]
https://github.com/donglee-afar/logdeep/issues/3#issuecomment-750028771
