### ISSUE TITLE
Bi-LSTM robustlog

### ISSUE THREAD

**Issue by KiteFlyKid** [donglee-afar/logdeep#17]
Nice implementation!
But why is the model of robustlog same as deeplog's?
In the original paper of robustlog, they use Bi-LSTM beside attention

**Comment by d0ng1ee** [comment]
I did not spend time trying Bi-LSTM,  code includes the attention module(which is commented )

**Comment by KiteFlyKid** [comment]
thx

**Comment by Heroning2019** [comment]
Nice implementation!
But how to get event2semantic_vec.json?
Using  sentence_transformers？

**Comment by d0ng1ee** [comment]
@Heroning2019 
https://github.com/donglee-afar/logdeep/issues/3#issuecomment-750028771
