### ISSUE TITLE
Question about LogAnomaly

### ISSUE THREAD

**Issue by yunsangq** [donglee-afar/logdeep#6]
Thank you for your work. It was very helpful.

I have a Two questions about LogAnomaly.

First,
When I read LogAnomaly paper there was Template2Vec Section.
But I can't find that part in your code.
There was a count vector part, but the sequence part does not seem to have Template2Vec applied.

Second,
Attention was implemented in the logdeep/models/lstm.py, but it was not used.

Again, Thanks for your work. :)

**Comment by d0ng1ee** [comment]
1. Template2Vec  is used in the actual application of a new log without a corresponding eventid, 
I did not implement it here, if you implement it, welcome Pr.
2.The attention mechanism(seems popular in papers in the nlp field) has little effect on My experimental results. I think i need update the model with attention part ......

**Comment by yunsangq** [comment]
Thank you for quick response!

It helped a lot  😄😄😄
